// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/home-variants/ActivityRings.tsx": () => import("../components/mockups/home-variants/ActivityRings.tsx"),
  "./components/mockups/home-variants/CoachMessage.tsx": () => import("../components/mockups/home-variants/CoachMessage.tsx"),
  "./components/mockups/home-variants/DashboardGrid.tsx": () => import("../components/mockups/home-variants/DashboardGrid.tsx"),
  "./components/mockups/home-variants/WorkoutHero.tsx": () => import("../components/mockups/home-variants/WorkoutHero.tsx")
};
